# Generated by Django 6.0.5 on 2026-05-29 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('susep_code', models.CharField(blank=True, max_length=50, verbose_name='registro SUSEP')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.brokerage', verbose_name='corretora')),
            ],
            options={
                'verbose_name': 'seguradora',
                'verbose_name_plural': 'seguradoras',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('brokerage', 'name'), name='unique_insurer_name_per_brokerage')],
            },
        ),
        migrations.CreateModel(
            name='LineOfBusiness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='código SUSEP')),
                ('category', models.CharField(choices=[('auto', 'Automotivo'), ('life', 'Vida'), ('property', 'Patrimonial'), ('business', 'Empresarial'), ('travel', 'Viagem'), ('health', 'Saúde'), ('other', 'Outro')], default='other', max_length=12, verbose_name='categoria')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.brokerage', verbose_name='corretora')),
            ],
            options={
                'verbose_name': 'ramo',
                'verbose_name_plural': 'ramos',
                'ordering': ('category', 'name'),
                'constraints': [models.UniqueConstraint(fields=('brokerage', 'name'), name='unique_lob_name_per_brokerage')],
            },
        ),
    ]
