# Generated by Django 6.0.5 on 2026-05-29 18:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('insurers', '0001_initial'),
        ('tenants', '0002_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('policy_number', models.CharField(max_length=50, verbose_name='número da apólice')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('canceled', 'Cancelada'), ('expired', 'Expirada'), ('renewed', 'Renovada')], default='active', max_length=10, verbose_name='status')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.brokerage', verbose_name='corretora')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='clients.client', verbose_name='cliente')),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='insurers.insurer', verbose_name='seguradora')),
                ('line_of_business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='insurers.lineofbusiness', verbose_name='ramo')),
            ],
            options={
                'verbose_name': 'apólice',
                'verbose_name_plural': 'apólices',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('number', models.CharField(max_length=50, verbose_name='número')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('sent', 'Enviada'), ('under_analysis', 'Em análise'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada'), ('converted', 'Convertida')], default='draft', max_length=15, verbose_name='status')),
                ('net_premium', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prêmio líquido')),
                ('total_premium', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prêmio total')),
                ('iof', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='IOF')),
                ('proposed_start_date', models.DateField(blank=True, null=True, verbose_name='início vigência proposto')),
                ('proposed_end_date', models.DateField(blank=True, null=True, verbose_name='fim vigência proposto')),
                ('payment_terms', models.CharField(blank=True, max_length=200, verbose_name='condições de pagamento')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('ai_summary', models.TextField(blank=True, default='', verbose_name='resumo IA')),
                ('ai_summary_status', models.CharField(choices=[('idle', 'Idle'), ('processing', 'Processando'), ('done', 'Concluído'), ('error', 'Erro')], default='idle', max_length=12, verbose_name='status resumo IA')),
                ('ai_summary_updated_at', models.DateTimeField(blank=True, null=True, verbose_name='resumo IA atualizado em')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.brokerage', verbose_name='corretora')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='clients.client', verbose_name='cliente')),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='insurers.insurer', verbose_name='seguradora')),
                ('line_of_business', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposals', to='insurers.lineofbusiness', verbose_name='ramo')),
            ],
            options={
                'verbose_name': 'proposta',
                'verbose_name_plural': 'propostas',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CoveredItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('item_type', models.CharField(choices=[('auto', 'Automotivo'), ('property', 'Patrimonial'), ('fleet', 'Frota'), ('travel', 'Viagem'), ('life', 'Vida'), ('equipment', 'Equipamento'), ('other', 'Outro')], default='other', max_length=12, verbose_name='tipo')),
                ('description', models.CharField(max_length=300, verbose_name='descrição')),
                ('identifier', models.CharField(blank=True, help_text='Placa, chassi, endereço, etc.', max_length=100, verbose_name='identificador')),
                ('insured_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='importância segurada')),
                ('attributes', models.JSONField(blank=True, default=dict, help_text='Dados específicos por tipo (JSON)', verbose_name='atributos')),
                ('coverages', models.JSONField(blank=True, default=list, help_text='Lista de coberturas e limites (JSON)', verbose_name='coberturas')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.brokerage', verbose_name='corretora')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='insurance.policy', verbose_name='apólice')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='insurance.proposal', verbose_name='proposta')),
            ],
            options={
                'verbose_name': 'item coberto',
                'verbose_name_plural': 'itens cobertos',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='policy',
            constraint=models.UniqueConstraint(fields=('brokerage', 'policy_number'), name='unique_policy_number_per_brokerage'),
        ),
        migrations.AddConstraint(
            model_name='proposal',
            constraint=models.UniqueConstraint(fields=('brokerage', 'number'), name='unique_proposal_number_per_brokerage'),
        ),
    ]
