# Generated by Django 6.0.5 on 2026-05-29 18:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='ai_summary',
            field=models.TextField(blank=True, default='', verbose_name='resumo IA'),
        ),
        migrations.AddField(
            model_name='policy',
            name='ai_summary_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('processing', 'Processando'), ('done', 'Concluído'), ('error', 'Erro')], default='idle', max_length=12, verbose_name='status resumo IA'),
        ),
        migrations.AddField(
            model_name='policy',
            name='ai_summary_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='resumo IA atualizado em'),
        ),
        migrations.AddField(
            model_name='policy',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='taxa de comissão (%)'),
        ),
        migrations.AddField(
            model_name='policy',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='fim vigência'),
        ),
        migrations.AddField(
            model_name='policy',
            name='iof',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='IOF'),
        ),
        migrations.AddField(
            model_name='policy',
            name='net_premium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prêmio líquido'),
        ),
        migrations.AddField(
            model_name='policy',
            name='payment_info',
            field=models.CharField(blank=True, max_length=300, verbose_name='informações de pagamento'),
        ),
        migrations.AddField(
            model_name='policy',
            name='proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='insurance.proposal', verbose_name='proposta de origem'),
        ),
        migrations.AddField(
            model_name='policy',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='início vigência'),
        ),
        migrations.AddField(
            model_name='policy',
            name='total_premium',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prêmio total'),
        ),
    ]
