# Generated by Django 6.0.5 on 2026-05-29 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0003_covereditem_covered_item_exactly_one_parent'),
        ('tenants', '0002_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endorsement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('endorsement_number', models.CharField(max_length=50, verbose_name='número do endosso')),
                ('type', models.CharField(choices=[('increase', 'Aumento'), ('decrease', 'Redução'), ('cancellation', 'Cancelamento'), ('data_change', 'Alteração Cadastral')], max_length=20, verbose_name='tipo')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('premium_change', models.DecimalField(decimal_places=2, default=0, help_text='Positivo para aumento, negativo para redução.', max_digits=14, verbose_name='variação de prêmio')),
                ('effective_date', models.DateField(verbose_name='data de vigência')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=20, verbose_name='status')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.brokerage', verbose_name='corretora')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endorsements', to='insurance.policy', verbose_name='apólice')),
            ],
            options={
                'verbose_name': 'endosso',
                'verbose_name_plural': 'endossos',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('brokerage', 'policy', 'endorsement_number'), name='unique_endorsement_number_per_policy')],
            },
        ),
    ]
