# Generated by Django 6.0.5 on 2026-05-29 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0004_endorsement'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='partners.agent', verbose_name='agente'),
        ),
        migrations.AddField(
            model_name='policy',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policies', to='partners.producer', verbose_name='produtor'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='partners.agent', verbose_name='agente'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='partners.producer', verbose_name='produtor'),
        ),
    ]
