# Generated by Django 6.0.5 on 2026-05-29 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0002_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('entity_type', models.CharField(choices=[('person', 'Pessoa Física'), ('company', 'Pessoa Jurídica')], default='person', max_length=10, verbose_name='tipo')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('document', models.CharField(db_index=True, max_length=18, verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('susep_code', models.CharField(blank=True, max_length=50, verbose_name='código SUSEP')),
                ('default_commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='taxa de comissão padrão (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.brokerage', verbose_name='corretora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_profiles', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'agente',
                'verbose_name_plural': 'agentes',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('entity_type', models.CharField(choices=[('person', 'Pessoa Física'), ('company', 'Pessoa Jurídica')], default='person', max_length=10, verbose_name='tipo')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('document', models.CharField(db_index=True, max_length=18, verbose_name='CPF/CNPJ')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='telefone')),
                ('default_commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='taxa de comissão padrão (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producers', to='partners.agent', verbose_name='agente')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.brokerage', verbose_name='corretora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producer_profiles', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'produtor',
                'verbose_name_plural': 'produtores',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='agent',
            constraint=models.UniqueConstraint(fields=('brokerage', 'document'), name='agent_unique_document_per_brokerage'),
        ),
        migrations.AddConstraint(
            model_name='producer',
            constraint=models.UniqueConstraint(fields=('brokerage', 'document'), name='producer_unique_document_per_brokerage'),
        ),
    ]
