# Generated by Django 6.0.5 on 2026-05-29 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=50, verbose_name='nome')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='preço')),
                ('is_available', models.BooleanField(default=False, verbose_name='disponível')),
                ('max_users', models.PositiveIntegerField(blank=True, null=True, verbose_name='máx. usuários')),
                ('max_clients', models.PositiveIntegerField(blank=True, null=True, verbose_name='máx. clientes')),
                ('max_policies', models.PositiveIntegerField(blank=True, null=True, verbose_name='máx. apólices')),
                ('features', models.JSONField(blank=True, default=list, verbose_name='funcionalidades')),
            ],
            options={
                'verbose_name': 'plano',
                'verbose_name_plural': 'planos',
                'ordering': ('price',),
            },
        ),
        migrations.CreateModel(
            name='Brokerage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('legal_name', models.CharField(max_length=200, verbose_name='razão social')),
                ('trade_name', models.CharField(blank=True, max_length=200, verbose_name='nome fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('susep_code', models.CharField(blank=True, max_length=50, verbose_name='registro SUSEP')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='telefone')),
                ('address_street', models.CharField(blank=True, max_length=200, verbose_name='logradouro')),
                ('address_number', models.CharField(blank=True, max_length=20, verbose_name='número')),
                ('address_city', models.CharField(blank=True, max_length=100, verbose_name='cidade')),
                ('address_state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('address_zip', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owned_brokerages', to=settings.AUTH_USER_MODEL, verbose_name='dono')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='brokerages', to='tenants.plan', verbose_name='plano')),
            ],
            options={
                'verbose_name': 'corretora',
                'verbose_name_plural': 'corretoras',
                'ordering': ('trade_name', 'legal_name'),
            },
        ),
    ]
