# Generated by Django 6.0.5 on 2026-05-29 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('status', models.CharField(choices=[('active', 'Ativa'), ('past_due', 'Em atraso'), ('canceled', 'Cancelada')], default='active', max_length=10, verbose_name='status')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='início em')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expira em')),
                ('brokerage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='tenants.brokerage', verbose_name='corretora')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='tenants.plan', verbose_name='plano')),
            ],
            options={
                'verbose_name': 'assinatura',
                'verbose_name_plural': 'assinaturas',
            },
        ),
    ]
