# Generated by Django 6.0.5 on 2026-05-29 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance', '0003_covereditem_covered_item_exactly_one_parent'),
        ('tenants', '0002_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('claim_number', models.CharField(max_length=50, verbose_name='número do sinistro')),
                ('occurrence_date', models.DateField(verbose_name='data da ocorrência')),
                ('notice_date', models.DateField(verbose_name='data do aviso')),
                ('status', models.CharField(choices=[('opened', 'Aberto'), ('under_analysis', 'Em Análise'), ('approved', 'Aprovado'), ('denied', 'Negado'), ('paid', 'Pago'), ('closed', 'Fechado')], default='opened', max_length=20, verbose_name='status')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('claimed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='valor reclamado')),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='valor aprovado')),
                ('ai_summary', models.TextField(blank=True, default='', verbose_name='resumo IA')),
                ('ai_summary_status', models.CharField(default='pending', max_length=20, verbose_name='status resumo IA')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.brokerage', verbose_name='corretora')),
                ('covered_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insurance.covereditem', verbose_name='item coberto')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insurance.policy', verbose_name='apólice')),
            ],
            options={
                'verbose_name': 'sinistro',
                'verbose_name_plural': 'sinistros',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('brokerage', 'claim_number'), name='claim_unique_number_per_brokerage')],
            },
        ),
    ]
