# Generated by Django 6.0.5 on 2026-05-29 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='ai_summary_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='resumo IA atualizado em'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='ai_summary_status',
            field=models.CharField(choices=[('idle', 'Idle'), ('processing', 'Processando'), ('done', 'Concluído'), ('error', 'Erro')], default='idle', max_length=12, verbose_name='status resumo IA'),
        ),
    ]
