# Generated by Django 6.0.5 on 2026-05-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_brokerage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('broker', 'Corretor'), ('agent', 'Agente'), ('producer', 'Produtor'), ('operational', 'Operacional')], default='operational', max_length=12, verbose_name='papel'),
        ),
    ]
