# Generated by Django 6.0.5 on 2026-05-29 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('insurance', '0005_policy_agent_policy_producer_proposal_agent_and_more'),
        ('insurers', '0001_initial'),
        ('partners', '0001_initial'),
        ('tenants', '0002_subscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('is_default', models.BooleanField(default=False, verbose_name='pipeline padrão')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.brokerage', verbose_name='corretora')),
            ],
            options={
                'verbose_name': 'pipeline',
                'verbose_name_plural': 'pipelines',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='valor estimado')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('won', 'Ganho'), ('lost', 'Perdido')], default='open', max_length=10, verbose_name='status')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='previsão de fechamento')),
                ('ai_summary', models.TextField(blank=True, default='', verbose_name='resumo IA')),
                ('ai_summary_status', models.CharField(default='pending', max_length=20, verbose_name='status resumo IA')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='partners.agent', verbose_name='agente')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.brokerage', verbose_name='corretora')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='clients.client', verbose_name='cliente')),
                ('insurer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='insurers.insurer', verbose_name='seguradora')),
                ('line_of_business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='insurers.lineofbusiness', verbose_name='ramo')),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='partners.producer', verbose_name='produtor')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='insurance.proposal', verbose_name='proposta')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='crm.pipeline', verbose_name='pipeline')),
            ],
            options={
                'verbose_name': 'negociação',
                'verbose_name_plural': 'negociações',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('color', models.CharField(default='#6c757d', max_length=7, verbose_name='cor (hex)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordem')),
                ('is_won', models.BooleanField(default=False, verbose_name='ganho')),
                ('is_lost', models.BooleanField(default=False, verbose_name='perdido')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.brokerage', verbose_name='corretora')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='crm.pipeline', verbose_name='pipeline')),
            ],
            options={
                'verbose_name': 'etapa',
                'verbose_name_plural': 'etapas',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='DealStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('note', models.TextField(blank=True, verbose_name='observação')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.brokerage', verbose_name='corretora')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='alterado por')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_histories', to='crm.deal', verbose_name='negociação')),
                ('from_stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='histories_from', to='crm.stage', verbose_name='etapa origem')),
                ('to_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories_to', to='crm.stage', verbose_name='etapa destino')),
            ],
            options={
                'verbose_name': 'histórico de etapa',
                'verbose_name_plural': 'históricos de etapa',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='crm.stage', verbose_name='etapa'),
        ),
    ]
