# Generated by Django 6.0.5 on 2026-05-29 18:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insurance', '0004_endorsement'),
        ('partners', '0001_initial'),
        ('tenants', '0002_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('base_premium', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='prêmio base')),
                ('insurer_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Percentual pago pela seguradora ao corretor.', max_digits=5, verbose_name='taxa da seguradora (%)')),
                ('insurer_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='valor recebido pela corretora')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('received', 'Recebida'), ('paid', 'Paga')], default='pending', max_length=20, verbose_name='status')),
                ('reference_date', models.DateField(blank=True, null=True, verbose_name='data de referência')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.brokerage', verbose_name='corretora')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='insurance.policy', verbose_name='apólice')),
            ],
            options={
                'verbose_name': 'comissão',
                'verbose_name_plural': 'comissões',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='CommissionSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('beneficiary_type', models.CharField(choices=[('agent', 'Agente'), ('producer', 'Produtor')], max_length=10, verbose_name='tipo de beneficiário')),
                ('rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, verbose_name='taxa de repasse (%)')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='valor do repasse')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago')], default='pending', max_length=20, verbose_name='status')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='pago em')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_splits', to='partners.agent', verbose_name='agente')),
                ('brokerage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.brokerage', verbose_name='corretora')),
                ('commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='commissions.commission', verbose_name='comissão')),
                ('producer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_splits', to='partners.producer', verbose_name='produtor')),
            ],
            options={
                'verbose_name': 'repasse',
                'verbose_name_plural': 'repasses',
                'ordering': ('-created_at',),
            },
        ),
    ]
